apiVersion: v1
kind: ServiceAccount
metadata:
  name: rust-k8s-test
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rust-k8s-test
subjects:
- kind: ServiceAccount
  name: rust-k8s-test
  namespace: default
roleRef:
  kind: ClusterRole
  name: rust-k8s-test
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rust-k8s-test
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - "list"
    - "watch"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rust-k8s-test
  namespace: default
spec:
  template:
    metadata:
      name: rust-k8s-test
      namespace: default
      labels:
        app: rust-k8s-test
    spec:
      containers:
      - name: rust-k8s-test
        image: rossf7/rust-k8s-test:dev
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: OnFailure
      serviceAccountName: rust-k8s-test
